# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# source generic shell scripts
source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/rc

# load all files from .config/shell/bashrc.d directory
if [ -d ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc.d ]; then
  for file in ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc.d/*; do
    source $file
  done
fi
