Lint/MissingCopEnableDirective:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: true
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Semicolon:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
