alt-tab
android-platform-tools
android-studio
bitwarden
browsers
caffeine
discord
eloston-chromium
font-symbols-only-nerd-font
gimp
jellyfin-media-player
karabiner-elements
localsend
maccy
notunes
obs
pika
podman-desktop
rectangle
syncthing
thunderbird
wezterm

# logseq
# db-browser-for-sqlite
# sonixd
# protonvpn
# mactex
