shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

# [plugins.zsh-syntax-hl]
# github = 'zsh-users/zsh-syntax-highlighting'
# apply = ["defer"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']
apply = ["defer"]

[plugins."z.lua"]
github = 'skywind3000/z.lua'
apply = ["defer"]

[plugins.forgit]
github = 'wfxr/forgit'
apply = ["defer"]

# [plugins.spaceship]
# github = 'spaceship-prompt/spaceship-prompt'

[plugins.substr-search]
github = 'zsh-users/zsh-history-substring-search'
apply = ["defer"]

[plugins.zsh-cmp]
github = 'zsh-users/zsh-completions'
apply = ["fpath"]

# [plugins.supercharge]
# github = 'zap-zsh/supercharge'

# [plugins.zap-prompt]
# github = 'zap-zsh/zap-prompt'

[plugins.zshrc-src]
local = "~/.config/zsh/src"

[plugins.zshrc-defer]
local = '~/.config/zsh/defer'
apply = ["defer"]

[plugins.zshrc-cmp]
local = '~/.config/zsh/cmp'
apply = ["fpath"]

[plugins.vim-ctrlz]
github = 'mdumitru/fancy-ctrl-z'
apply = ["defer"]

[plugins.fast-syntax-hl]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.zinsults]
github = 'ahmubashshir/zinsults'

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
