shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

# [plugins.spaceship]
# github = 'spaceship-prompt/spaceship-prompt'

# [plugins.zsh-syntax-hl]
# github = 'zsh-users/zsh-syntax-highlighting'
# apply = ["defer"]

[plugins.fast-syntax-hl]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']
apply = ["defer"]

# [plugins."z.lua"] # replaced by zoxide
# github = 'skywind3000/z.lua'
# apply = ["defer"]

# [plugins.fz]
# github = 'changyuheng/fz'
# apply = ['defer']

[plugins.forgit]
github = 'wfxr/forgit'
apply = ["defer"]

[plugins.substr-search]
github = 'zsh-users/zsh-history-substring-search'
apply = ["defer"]

[plugins.zsh-cmp]
github = 'zsh-users/zsh-completions'
apply = ["fpath"]

[plugins.zshrc-src]
local = "~/.config/zsh/src"

[plugins.zsh-cfg-defer]
local = '~/.config/shell/defer'
apply = ["defer"]

[plugins.zshrc-cmp]
local = '~/.config/shell/cmp'
apply = ["fpath"]

[plugins.vim-ctrlz]
github = 'mdumitru/fancy-ctrl-z'
apply = ["defer"]

# [plugins.zinsults]
# github = 'ahmubashshir/zinsults'
# apply = ['defer']

[plugins.zsh-notify]
github = 'marzocchi/zsh-notify'
apply = ['defer']

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
