theme = "tokyonight_storm"

[editor]
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]


# Muscle memory
G = "goto_file_end"
0 = "goto_line_start"
Y = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
]
# "$" = "goto_line_end"

# Personal preference
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
# "^" = "goto_first_nonwhitespace"
# "%" = "match_brackets"
# V = ["select_mode", "extend_to_line_bounds"]
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
# D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
# S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

# Clipboards over registers ye ye
# x = "delete_selection"
# p = ["paste_clipboard_after", "collapse_selection"]
# P = ["paste_clipboard_before", "collapse_selection"]
# Would be nice to add ya and yi, but the surround commands can't be chained
# Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]


[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"
