theme = "tokyonight"

[editor]
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
# makes 'extend_line' infinitely more useful
I = ["split_selection_on_newline","insert_at_line_start"]
A = ["split_selection_on_newline","insert_at_line_end"]

# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"

# Muscle memory
G = "goto_file_end"
0 = "goto_line_start"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

Y = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
]

# Some nice Helix stuff
C-h = "select_prev_sibling"
S-ret = "shrink_selection"
ret = "expand_selection"
C-l = "select_next_sibling"

[keys.normal.g]
q = ":reflow"
"[" = ["hsplit","jump_view_up","goto_definition"]
"]" = ["vsplit","jump_view_up","goto_definition"]

[keys.normal.space]
q = ":quit"
w = ":write"
