return {
  mason_lsp = {
    "lua_ls",
    "rust_analyzer",
    "phpactor",
    "jsonls",
    "tsserver",
    -- "denols",
  },
  external = {
    -- "rust_analyzer",
  },
  mason = {
    "stylua",
    "prettierd",
  },
  -- "bashls",
  -- "clangd",
  -- "csharp_ls",
  -- "cmake",
  -- "cssls",
  -- "denols",
  -- "dockerls",
  -- "emmet_ls",
  -- "gopls",
  -- "gradle_ls",
  -- "html",
  -- "jsonls",
  -- "jdtls",
  -- "tsserver",
  -- "kotlin_language_server",
  -- "lua_ls",
  -- "remark_ls",
  -- "intelephense",
  -- "pyright",
  -- "ruby_ls",
  -- "sqlls",
  -- "taplo",
  -- "teal_ls",
  -- "vls",
  -- "vimls",
  -- "yamlls",
  -- "zls",
}
